export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const POST_PERSONAL_INFORMATION_SUCCESS =
  'POST_PERSONAL_INFORMATION_SUCCESS';

export const POST_PERSONAL_INFORMATION_FAIL = 'POST_PERSONAL_INFORMATION_FAIL';
export const GET_STATE_SUCCESS = 'GET_STATE_SUCCESS';
export const GET_STATE_FAIL = 'GET_STATE_FAIL';
export const GET_LGA_SUCCESS = 'GET_LGA_SUCCESS';
export const GET_LGA_FAIL = 'GET_LGA_FAIL';
export const SUBMIT_PERSONAL_INFORMATION = 'SUBMIT_PERSONAL_INFORMATION';
export const FORM_LOADING_TRUE = 'FORM_LOADING_TRUE';
export const FORM_LOADING_FALSE = 'FORM_LOADING_FALSE';
export const POST_VALIDATE_PHONE_SUCCESS = 'POST_VALIDATE_PHONE_SUCCESS';
export const POST_VALIDATE_PHONE_FAIL = 'POST_VALIDATE_PHONE_FAIL';
export const SUBMIT_TOKEN = 'SUBMIT_TOKEN';

export const POST_MEANS_OF_IDENTIFICATION_SUCCESS =
  'POST_MEANS_OF_IDENTIFICATION_SUCCESS';
export const POST_MEANS_OF_IDENTIFICATION_FAIL =
  'POST_MEANS_OF_IDENTIFICATION_FAIL';
export const GET_ID_TYPE_SUCCESS = 'GET_ID_TYPE_SUCCESS';
export const GET_ID_TYPE_FAIL = 'GET_ID_TYPE_FAIL';
export const SUBMIT_MEANS_OF_IDENTIFICATION = 'SUBMIT_MEANS_OF_IDENTIFICATION';
export const POST_BUSINESS_INFORMATION_SUCCESS =
  'POST_BUSINESS_INFORMATION_SUCCESS';
export const POST_BUSINESS_INFORMATION_FAIL = 'POST_BUSINESS_INFORMATION_FAIL';
export const SUBMIT_BUSINESS_INFORMATION = ' SUBMIT_BUSINESS_INFORMATION';
export const POST_SECURITY_DETAILS_SUCCESS = ' POST_SECURITY_DETAILS_SUCCESS';
export const POST_SECURITY_DETAILS_FAIL = ' POST_SECURITY_DETAILS_FAIL';
